#!/usr/bin/env bash
# format-on-stop.sh — Stop hook: informational code-quality check (non-blocking).
#
# Runs the project's fast formatting/lint checks (ruff format and ruff check) over the
# source trees using the project venv, and prints a summary at turn-end. It is
# advisory: it always exits 0 so it never blocks a turn. The git pre-commit hook
# remains the source of truth; this just surfaces drift early.
#
# Project specifics: line length 100; src/bestehorn_llmmanager/_version.py is
# auto-generated by setuptools-scm and is ALWAYS excluded from every check (via the
# extend-exclude in [tool.ruff] in pyproject.toml).

set -u

ROOT="${CLAUDE_PROJECT_DIR:-$(pwd)}"
cd "$ROOT" || exit 0

# Locate the venv tools (Windows layout first, then *nix).
if [[ -x "$ROOT/venv/Scripts/ruff.exe" ]]; then
  BIN="$ROOT/venv/Scripts"
  EXT=".exe"
elif [[ -x "$ROOT/venv/bin/ruff" ]]; then
  BIN="$ROOT/venv/bin"
  EXT=""
else
  echo "format-on-stop: venv not found — skipping advisory format check." >&2
  exit 0
fi

TARGETS=()
for d in src test scripts; do
  [[ -d "$ROOT/$d" ]] && TARGETS+=("$d")
done
[[ ${#TARGETS[@]} -eq 0 ]] && exit 0

status=0
echo "format-on-stop: advisory ruff check (line-length 100, _version.py excluded)" >&2

"$BIN/ruff$EXT" format --check --quiet "${TARGETS[@]}" >&2 2>&1 || { echo "  -> ruff format would reformat files (run: ruff format ${TARGETS[*]})" >&2; status=1; }
"$BIN/ruff$EXT" check --quiet "${TARGETS[@]}" >&2 2>&1 || { echo "  -> ruff check reported issues (run: ruff check --fix ${TARGETS[*]})" >&2; status=1; }

[[ $status -eq 0 ]] && echo "  -> clean." >&2

# Always non-blocking.
exit 0
