#!/usr/bin/env bash
# format-on-stop.sh — Stop hook: informational code-quality check (non-blocking).
#
# Runs the project's fast formatting/lint checks (black + isort + flake8) over the
# source trees using the project venv, and prints a summary at turn-end. It is
# advisory: it always exits 0 so it never blocks a turn. The git pre-commit hook
# remains the source of truth; this just surfaces drift early.
#
# Project specifics: line length 100; src/bestehorn_llmmanager/_version.py is
# auto-generated by setuptools-scm and is ALWAYS excluded from every check.

set -u

ROOT="${CLAUDE_PROJECT_DIR:-$(pwd)}"
cd "$ROOT" || exit 0

# Locate the venv tools (Windows layout first, then *nix).
if [[ -x "$ROOT/venv/Scripts/black.exe" ]]; then
  BIN="$ROOT/venv/Scripts"
  EXT=".exe"
elif [[ -x "$ROOT/venv/bin/black" ]]; then
  BIN="$ROOT/venv/bin"
  EXT=""
else
  echo "format-on-stop: venv not found — skipping advisory format check." >&2
  exit 0
fi

EXCLUDE="src/bestehorn_llmmanager/_version.py"
TARGETS=()
for d in src test scripts; do
  [[ -d "$ROOT/$d" ]] && TARGETS+=("$d")
done
[[ ${#TARGETS[@]} -eq 0 ]] && exit 0

status=0
echo "format-on-stop: advisory black/isort/flake8 check (line-length 100, _version.py excluded)" >&2

"$BIN/black$EXT" "${TARGETS[@]}" --check --quiet --extend-exclude="$EXCLUDE" >&2 2>&1 || { echo "  -> black would reformat files (run: black ${TARGETS[*]} --extend-exclude=\"$EXCLUDE\")" >&2; status=1; }
"$BIN/isort$EXT" "${TARGETS[@]}" --check-only --quiet --skip="$EXCLUDE" >&2 2>&1 || { echo "  -> isort would reorder imports (run: isort ${TARGETS[*]} --skip=\"$EXCLUDE\")" >&2; status=1; }
"$BIN/flake8$EXT" "${TARGETS[@]}" --max-line-length=100 --extend-ignore=E203,W503 --exclude="$EXCLUDE" >&2 2>&1 || { echo "  -> flake8 reported issues" >&2; status=1; }

[[ $status -eq 0 ]] && echo "  -> clean." >&2

# Always non-blocking.
exit 0
