#!/usr/bin/env bash
# scripts/setup-hooks.sh — installs a project-local pre-commit hook.
#
# Why this pattern: the standard `pre-commit install` writes a hook that depends on the
# system PATH. On a machine that hosts multiple Python projects, that PATH is unreliable
# — especially when git is invoked from an IDE or GUI client that does not activate the
# venv. This script writes a hook that hardcodes the absolute path to the project's venv
# `pre-commit` executable, sidestepping all PATH resolution concerns. Run once per clone.
#
# The generated hook runs only the FAST checks (ruff-check + ruff-format). Slow checks
# (mypy, pytest) are left for CI or manual invocation.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" || "$OSTYPE" == "win32" ]]; then
    PRECOMMIT_PATH="$PROJECT_ROOT/venv/Scripts/pre-commit.exe"
else
    PRECOMMIT_PATH="$PROJECT_ROOT/venv/bin/pre-commit"
fi

if [ ! -x "$PRECOMMIT_PATH" ]; then
    echo "ERROR: pre-commit not found at $PRECOMMIT_PATH" >&2
    echo "Run: pip install -e '.[dev]' inside an activated venv first." >&2
    exit 1
fi

cat > "$PROJECT_ROOT/.git/hooks/pre-commit" << HOOK
#!/usr/bin/env bash
# Auto-generated by scripts/setup-hooks.sh — do not edit by hand.
# Pre-commit hook with absolute venv path to avoid PATH issues.
# Runs only fast checks (ruff-check + ruff-format). Slow checks (mypy, pytest)
# are left for CI or manual invocation.
PRECOMMIT="$PRECOMMIT_PATH"
if [ ! -x "\$PRECOMMIT" ]; then
    echo "ERROR: pre-commit not found at \$PRECOMMIT" >&2
    echo "Recreate venv: python -m venv venv && pip install -e '.[dev]'" >&2
    exit 1
fi
"\$PRECOMMIT" run ruff-check --config "$PROJECT_ROOT/.pre-commit-config.yaml" || exit \$?
exec "\$PRECOMMIT" run ruff-format --config "$PROJECT_ROOT/.pre-commit-config.yaml"
HOOK

chmod +x "$PROJECT_ROOT/.git/hooks/pre-commit"
echo "Pre-commit hook installed at $PROJECT_ROOT/.git/hooks/pre-commit"
echo "Using venv pre-commit: $PRECOMMIT_PATH"
